model = Model(false);
cam = Camera();
pos = Lab2Step2();
robot = Robot();
I = cam.getImage();
imshow(I);
p = ginput(1);
joint_vars = robot.read_joint_vars(true,false,true);
model.fk(joint_vars);
a = pos.Lab5Step2(p(1),p(2),cam);